# CONTAINER_START_PATH is passed as an env var when the container is created it is passed to the current user via the root environment (see sudoers)

if [ -z "$CONTAINER_START_PATH" ]; then
    echo "Using default start path"
    export CONTAINER_START_PATH="/root"
fi  

if [ -z "$USER" ]; then
    export USER=$(id -nu $UID)
fi

if [ -z "$HOME" ]; then
    export HOME="/root"
fi

echo "HOME=$HOME, USER=$USER, UID=$UID"
echo "CONTAINER_START_PATH: $CONTAINER_START_PATH"
cd "$CONTAINER_START_PATH"
source $HOME/.bashrc

# override user installed conda to use container
# based conda
export PATH=/opt/conda/bin:$PATH
source activate py3
